image: alpine/edge
packages:
  - hugo
  - rsync
sources:
  - https://git.sr.ht/~codebam/seanbehan.ca
environment:
  deploy: codebam@ssh.seanbehan.ca
secrets:
  - fc873c0d-1f24-4cf0-8a61-9601d355a887
tasks:
  - build: |
      cd seanbehan.ca
      hugo
  - deploy: |
      cd seanbehan.ca
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rP public/ $deploy:~/seanbehan.ca --delete
