baseURL = "/"
relativeURLs = true
languageCode = "en-us"
title = "Sean Behan"
theme = "etch-custom"

enableInlineShortcodes = true
uglyurls = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "Sean Behan's personal website"
src = "https://github.com/codebam/seanbehan.ca"
copyright = "Copyright ©2018-2022 Sean Behan"
dark = "auto"
highlight = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about.html"
  [[menu.main]]
    identifier = "portfolio"
    name = "portfolio"
    url = "https://github.com/codebam"
  [[menu.main]]
    identifier = "rss"
    name = "rss"
    url = "/posts/index.xml"

[permalinks]
posts = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[markup.tableOfContents]
ordered = true

[outputs]
section = ["HTML", "RSS"]
