baseURL = "/"
languageCode = "en-us"
title = "Sean Behan"
theme = "etch-custom"

enableInlineShortcodes = true
# disablePathToLower = true
uglyurls = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "Sean Behan's personal website"
src = "https://github.com/codebam/seanbehan.dev"
copyright = "Copyright © 2020 Sean Behan"
dark = "auto"
highlight = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about.html"
  [[menu.main]]
    identifier = "git"
    name = "git"
    url = "https://github.com/codebam"
  [[menu.main]]
    identifier = "rss"
    name = "rss"
    url = "/posts/index.xml"

[permalinks]
posts = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[markup.tableOfContents]
ordered = true

# lifted from https://git.sr.ht/~sircmpwn/drewdevault.com
[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
name = "GEMTEXT"
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"

[outputFormats.GEMRSS]
name = "GEMRSS"
isHTML = false
mediaType = "application/rss+xml"
protocol = "gemini://"
path = "gemini/"

[outputs]
section = ["HTML", "RSS", "GEMRSS"]
