baseURL = "/"
relativeURLs = true
languageCode = "en-ca"
title = "Sean Behan"
theme = "etch-custom"

enableInlineShortcodes = true
uglyurls = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "Sean Behan's personal website"
src = "https://github.com/codebam/codebam.github.io"
copyright = "Copyright ©2018-2022 Sean Behan"
dark = "auto"
highlight = false

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "portfolio"
    url = "https://github.com/codebam"
  [[menu.main]]
    identifier = "resumé"
    name = "resume"
    url = "/resume.html"
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact.html"
  [[menu.main]]
    identifier = "gaming"
    name = "gaming"
    url = "/gaming.html"

[permalinks]
posts = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[markup.tableOfContents]
ordered = true

[outputs]
section = ["HTML", "RSS"]
